### ISSUE TITLE
Height/Layout Portrait Mode

### ISSUE THREAD

**Issue by cass00** [SebastianLuebke/improved-osk-gnome-ext#1]
Thanks for your extension. Would it be possible to include some adjustment for the height/layout in portrait mode. At the moment it is not ideal on my X1 tablet (see screenshot below). Would be nice if one could increase the height, by for example, changing the aspect ratio of the keys.

 There's some other extension (https://github.com/jlempen/gnome-shell-osk-tweaks) that can do it apparently. However it is not working for Gnome 3.36.

![image](https://user-images.githubusercontent.com/16628330/86496514-12f81a80-bd7e-11ea-9095-45d8d2e69839.png)

**Comment by luebke-dev** [comment]
Yes, I already got a version that allows to set the keyboard box height. Just need to finish the settings panel. Should be available by Monday.

I also plan to make the layout more configurable, but this could take some time.
