### ISSUE TITLE
It only works on Wayland?

### ISSUE THREAD

**Issue by tiotrom** [SebastianLuebke/improved-osk-gnome-ext#3]
If so, any plans to make it work on Xorg too?

**Comment by luebke-dev** [comment]
:D it works best on xorg. wayland is currently bugged. What doesnt work for you?

**Comment by tiotrom** [comment]
Ok after several tests and installing that recommended font + disabling the onscreen keyboard from gnome settings it works. However is kinda buggy. Especially when you try to minimize the keyboard. Also, it is not triggered when editing a text. I know this is offtopic but https://launchpad.net/onboard is such an amazing project and so far the best on-screen keyboard that I tested and so featured rich. But seems not to be maintained anymore. If you had the knowledge to contribute to that one could be fantastic. Linux lacks a proper onscreen keyboard that is simple to use, it is triggered by text-editing events, it learns while you type, suggest words and such basic functionalities that onboard has but this one or the gnome default lack.

I am managing TROMjaro and I am testing it a lot on touchscreen devices this is why I got interested in your extension.

Cheers!

**Comment by luebke-dev** [comment]
Actually you dont have disable the keyboard in gnome. By default the gnome osk pops up when the last input event was triggered by a touchscreen. enabling the keyboard in the gnome accessibility settings just allows it to pop up on non touch input events.

On wayland the gnome osk keyboard is bugged for some apps, but i couldnt find the reason for it for now. 

What is buggy when you try to minimize the keyboard? im using manjaro gnome and dont have any problems at all.

**Comment by tiotrom** [comment]
Ok I see. For me it is still buggy like I explained above. When I try to minimize the keyboard it doesn't minimize and/or the original one is underneath.

**Comment by luebke-dev** [comment]
mhh thats really strange. i will download tromjaro to check if i can reproduce the error.

**Comment by luebke-dev** [comment]
Tromjaro doesnt work at all on my pc. Gnome keeps crashing on first start.

**Comment by tiotrom** [comment]
I am sorry I just saw this message. If you use the latest TROMjaro it should work. We have a chat at tromsite.com/chat in case you need any help. I apologize again for the late reply, it seems that the notification for this post didn't go through.
