### ISSUE TITLE
Not working in activities and password modal for Gnome 3.36.6

### ISSUE THREAD

**Issue by cass00** [SebastianLuebke/improved-osk-gnome-ext#5]
Keyboard appears but input is somehow ignored.

**Comment by luebke-dev** [comment]
mhh doesnt even work with the original gnome osk

**Comment by luebke-dev** [comment]
opened an issue at https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3187

**Comment by luebke-dev** [comment]
looks like no one cares about it at gnome. I will do some digging on the weekend. hopefully I will find the breaking changes

**Comment by luebke-dev** [comment]
i freshly reinstalled manjaro gnome on my desktop and the modals are working again.

edit: now using wayland, dont know if the bug is only related to x11

**Comment by cass00** [comment]
Does it also work if you switch to X11? Are you still on the same gnome version Gnome (3.36.6) ?
