### ISSUE TITLE
Version for Gnome 3.38?

### ISSUE THREAD

**Issue by AxelMKlein** [SebastianLuebke/improved-osk-gnome-ext#7]
Hi Sebastian,

First, thank you very much for this excellent piece of software! This is a great relief when working with Ubuntu Gnome on a 2-in-1 laptop with touchscreen.

Will there be a dedicated version for Gnome 3.38?

Best regards

**Comment by luebke-dev** [comment]
yeah, I'm already waiting for gnome 3.38 on manjaro. maybe I should switch back to plain arch linux

**Comment by luebke-dev** [comment]
should work now. im using 3.38 without problems
